### PR TITLE
Updated Readme to add installation and setup instructions.

### PR DESCRIPTION
**Pull request by trgardos**

### CODE REVIEW

**Comment by mcrovella** [comment]
Hi Tom - Thanks, these are super helpful (for me as well as for others).   One thing, can we change the environment name from markc to something generic like DS701?

**Comment by trgardos** [comment]
Sure. Will do.

From: Mark Crovella ***@***.***>
Date: Monday, October 2, 2023 at 10:58 AM
To: mcrovella/DS701-Tools-for-Data-Science ***@***.***>
Cc: Gardos, Thomas ***@***.***>, Author ***@***.***>
Subject: Re: [mcrovella/DS701-Tools-for-Data-Science] Updated Readme to add installation and setup instructions. (PR #2)

Hi Tom - Thanks, these are super helpful (for me as well as for others). One thing, can we change the environment name from markc to something generic like DS701?

**Comment by trgardos** [comment]
Just checked and there is no mention of the environment `markc`. Perhaps you saw that in the commit history? I have a more expansive readme with the latest Python, but I deleted that content for now. 

If and when you do merge, I suggest you squash the commits, since I added content and then removed it.

**Comment by mcrovella** [comment]
Oh, got it … yes you are right.  Thanks.

From: Thomas (Tom) Gardos ***@***.***>
Date: Monday, October 2, 2023 at 2:21 PM
To: mcrovella/DS701-Tools-for-Data-Science ***@***.***>
Cc: Mark Crovella ***@***.***>, Comment ***@***.***>
Subject: Re: [mcrovella/DS701-Tools-for-Data-Science] Updated Readme to add installation and setup instructions. (PR #2)

Just checked and there is no mention of the environment markc. Perhaps you saw that in the commit history? I have a more expansive readme with the latest Python, but I deleted that content for now.

If and when you do merge, I suggest you squash the commits, since I added content and then removed it.

**Pull request merged**
